spring.application.name=restapi

server.port=${EMP_SERVER_PORT}
logging.level.org.springframework.security=DEBUG

# Database Related Variables
spring.datasource.url=${EMP_DB_URL}
spring.datasource.username=${EMP_DB_USERNAME}
spring.datasource.password=${EMP_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.ddl-auto=update

api.url.mapping=/api/v1.0.0/employee

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=trace